base_url: 'https://regolith-linux.crowdin.com'
preserve_hierarchy: true
files:
  - source: /content/en/**/*.md
    translation: /content/%two_letters_code%/**/%original_file_name%
    type: fm_md
    ignore:
      - /content/en/search-index.md
    two_letters_code:
      zh-CN: zh_CH
      zh-TW: zh_tw
      pt-BR: pt_br
      pt-PT: pt
  - source: /i18n/en.json
    translation: /i18n/%two_letters_code%.json
    type: json
    two_letters_code:
      zh-CN: zh_CH
      zh-TW: zh_tw
      pt-BR: pt_br
      pt-PT: pt

